sudo:
  - yes

before_install:
  - npm i -g npm@6.4.1
  - sudo chmod +x ./WebPhapp/PharmaChain/install_travis.sh
  - sudo chmod +x ./testRunner.sh

language: node_js

node_js:
  - "8"

script:
  - sudo ./WebPhapp/PharmaChain/install_travis.sh
  - sudo ./testRunner.sh

cache:
  directories:
    - node_modules
